baseurl: "/"
title: "Stackbit Book Theme"
init_js: "js/init.js"
page_load_js: "js/page-load.js"
page_unload_js: "js/page-unload.js"
params:
  layout_type: boxed
  style: classic
  palette: gray
  mode: light
  base_font: serif
  header:
    title: Marketing Playbook
    logo: images/logo.svg
    logo_alt: Marketing Playbook logo
    has_primary_nav: true
    primary_nav_links:
      - label: Pricing
        url: /pricing
        style: link
      - label: Story
        url: /story
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - label: Start Learning
        url: /thank-you
        style: primary
    has_anncmnt: true
    anncmnt_content: >-
      Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn More](/pricing/)**
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    logo: images/logo.svg
    logo_alt: Marketing Playbook logo
    has_primary_nav: true
    primary_nav_title: Company
    primary_nav_links:
      - label: Story
        url: /story
        style: link
      - label: Pricing
        url: /pricing
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_title: Legal
    secondary_nav_links:
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_tertiary_nav: false
    has_social: true
    social_links:
      - label: Twitter
        url: https://twitter.com/
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - label: Facebook
        url: https://www.facebook.com/
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
      - label: YouTube
        url: https://www.youtube.com/
        style: link
        has_icon: true
        icon: youtube
        icon_position: center
        new_window: true
      - label: Vimeo
        url: https://vimeo.com/
        style: link
        has_icon: true
        icon: vimeo
        icon_position: center
        new_window: true
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with <a href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank" rel="noopener">Stackbit</a>. Create yours <a href="https://app.stackbit.com/create?theme=book&utm_source=deployed-footer" target="_blank" rel="noopener">now</a>
sass:
  input_file: sass/main.scss
  output_file: css/main.css
  indentWidth: 4
  outputStyle: expanded
  precision: 10
templates:
  body_class: "layout-{{ site.params.layout_type }} style-{{ site.params.style }} palette-{{ site.params.palette }} mode-{{ site.params.mode }} font-{{ site.params.base_font }}"
